directories:
  output: release
  buildResources: build
appId: com.bioryx.app
productName: Bioryx
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - package.json
win:
  target: nsis
  icon: assets/logo.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 42.4.1
